import { Shot } from "../RootContainer";

export const topShots: Array<Shot | undefined> = [
  {
    clubName: "Putter",
    holeDistance: 387,
    holeId: 1,
    holePar: 4,
    holeScore: 4,
    shotCategory: "ARG",
    shotDistance: 16.027136,
    shotEndLie: "GREEN",
    shotId: 3,
    shotQuality: 137.63185,
    shotStartLie: "FAIRWAY",
    shotType: "ARG",
  },
  {
    clubName: "Driver",
    holeDistance: 402,
    holeId: 6,
    holePar: 4,
    holeScore: 5,
    shotCategory: "TEE",
    shotDistance: 246.61378,
    shotEndLie: "FAIRWAY",
    shotId: 1,
    shotQuality: 101.371666,
    shotStartLie: "TEE",
    shotType: "TEE",
  },
  {
    clubName: "9 Iron",
    holeDistance: 145,
    holeId: 13,
    holePar: 3,
    holeScore: 3,
    shotCategory: "APP",
    shotDistance: 134.59029,
    shotEndLie: "GREEN",
    shotId: 1,
    shotQuality: 96.4686,
    shotStartLie: "TEE",
    shotType: "GOING_FOR_GREEN",
  },
];
